### ISSUE TITLE
Code predicting seed 'None' when tested towards random.random?

### ISSUE THREAD

**Issue by N0K0** [deut-erium/RNGeesus#2]
Hi! Been trying to run towards random.random, but the predictor is just returning None.

Note, mersenne.py has been saved as `rngeesus.py`

Any tips would be appreciated!

```py
from rngeesus import Breaker
from random import Random
from secrets import randbits


def sample():
    print("Sampling...")

    correct = 0
    iterations = 10000
    for _ in range(iterations):
        seed = randbits(32)

        rng = Random(seed)

        # Empty the RNG that is filled from /dev/urandom
        # I think this is necessary to get a predictable RNG
        for _ in range(624):
            rng.getrandbits(32)

        b = Breaker()
        # Two values in the format (index, value)
        vals = [
            (0, rng.getrandbits(32)),
            (1, rng.getrandbits(32)),
            (2, rng.getrandbits(32)),
        ]

        print(vals)
        print("Predicting...")

        # This line always returns None for some reason?
        recovered_seed = b.get_seed_mt(vals)

        # Get the next value from the RNG
        # We will use this to check if the predictor is correct
        print(f"Actual seed: {seed}")
        print(f"Predicted seed: {recovered_seed}")

        if recovered_seed == seed:
            print("Correct!")
            correct += 1

        print(f"Current status: {correct}/{iterations}")

    print(f"Correct: {correct}/{iterations}")


if __name__ == "__main__":
    sample()

```

**Comment by deut-erium** [comment]
Hi @N0K0 I am trying to understand what are you trying to do here.
```
# Empty the RNG that is filled from /dev/urandom
# I think this is necessary to get a predictable RNG
```
I think your understanding of python random.Random is different
You can check out how initialization is done in [this link](https://github.com/python/cpython/blob/6b961b8ceaba372b78d03feaceb4837bf7236694/Modules/_randommodule.c#L218)

Also, you are mixing the seed cracking in numpy random and python random (which use slightly different initializations)
To recover the seed in python random, you will need 624 values nevertheless, check the [test file](https://github.com/deut-erium/RNGeesus/blob/007e921e8f99d32ff9ff958a55bd886a5cbf1ddf/src/code_mersenne/test_mersenne.py#L146) for example
